server:
  port: 8081
spring:
  application:
    name: product-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///shop-product?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456test!
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  zipkin:
    base-url: http://127.0.0.1:9411/ #zipkin server请求地址
    discovery-client-enabled: false    #让nacos把它当成URL,而非服务名
  sleuth:
    sampler:
      probability: 1.0 #采样比

